language: android
jdk: oraclejdk8

android:
  components:

    - build-tools-25.0.3

    - android-25

    - extra-google-m2repository
    - extra-android-m2repository

    - tools
    - platform-tools